query getAlbum($id: ID!, $options: PageQueryOptions) {
  album(id: $id) {
    id
    title
    user {
      id
      name
    }
    photos(options: $options) {
      data {
        id
        title
        thumbnailUrl
        url
      }
      meta {
        totalCount
      }
    }
  }
}
