query getAlbumInput($id: ID!) {
  album(id: $id) {
    id
    title
    user {
      id
    }
  }
}

mutation updateAlbum($id: ID!, $input: UpdateAlbumInput!) {
  updateAlbum(id: $id, input: $input) {
    id
  }
}
